"project_id" : "431304"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "Localization/Crowdin/"
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
 {
  "source" : "app.json",
  "translation" : "translation/%locale_with_underscore%/%original_file_name%",
  "update_option" : "update_as_unapproved",
  "skip_untranslated_strings" : false,
 },
 {
  "source" : "app.stringsdict",
  "translation" : "translation/%locale_with_underscore%/%original_file_name%",
  "update_option" : "update_as_unapproved",
  "skip_untranslated_strings" : false,
 },
 {
  "source" : "ios-infoPlist.json",
  "translation" : "translation/%locale_with_underscore%/%original_file_name%",
  "update_option" : "update_as_unapproved",
  "skip_untranslated_strings" : false,
 }
]