name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/*
  pull_request:
    branches:
    - develop

# macOS environments: https://github.com/actions/virtual-environments/tree/main/images/macos

jobs:
  build:
    name: CI Build Test
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: force Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
        
      - name: setup
        env: 
            AppSecret: ${{ secrets.AppSecret }}
            HostKeyPublic: ${{ secrets.HostKeyPublic }}
            ConsumerKeyDebug: ${{ secrets.ConsumerKeyDebug }}
            ConsumerKeyRelease: ${{ secrets.ConsumerKeyRelease }}
            ConsumerKeySecretDebug: ${{ secrets.ConsumerKeySecretDebug }}
            ConsumerKeySecretRelease: ${{ secrets.ConsumerKeySecretRelease }}
            OauthEndpointDebug: ${{ secrets.OauthEndpointDebug }}
            OauthEndpointRelease: ${{ secrets.OauthEndpointRelease }}
            ClientIDDebug: ${{ secrets.ClientIDDebug }}
            ClientIDRelease: ${{ secrets.ClientIDRelease }}
            ClientSecretDebug: ${{ secrets.ClientSecretDebug }}
            ClientSecretRelease: ${{ secrets.ClientSecretRelease }}
            Oauth2EndpointDebug: ${{ secrets.Oauth2EndpointDebug }}
            Oauth2EndpointRelease: ${{ secrets.Oauth2EndpointRelease }}
            MastodonNotificationEndpointDebug: ${{ secrets.MastodonNotificationEndpointDebug }}
            MastodonNotificationEndpointRelease: ${{ secrets.MastodonNotificationEndpointRelease }}
        run: exec ./.github/scripts/setup.sh

      - name: build
        run: exec ./.github/scripts/build-debug.sh
