name: Build and Release

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

# macOS environments: https://github.com/actions/virtual-environments/tree/main/images/macos

jobs:
  build:
    name: Release
    runs-on: macos-11
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0    # https://github.com/Khan/pull-request-comment-trigger
        id: check
        with:
          trigger: '#r2d2/release'
          prefix_only: true
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
      
      # https://docs.github.com/en/enterprise-server@3.3/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
      - name: Import Code-Signing Certificates            
        uses: Apple-Actions/import-codesign-certs@v1      # https://github.com/Apple-Actions/import-codesign-certs
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: checkout
        uses: actions/checkout@v2

      - name: force Xcode 13.2
        run: sudo xcode-select -switch /Applications/Xcode_13.2.app

      - name: setup
        run: exec ./.github/scripts/setup.sh

      - name: build
        run: exec ./.github/scripts/build.sh
